apiVersion: apps/v1
kind: Deployment
metadata:
  name: uav-api-deployment
  labels:
    k8s-app: uav-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: uav-api
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxSurge: 55%
    maxUnavailable: 30%
  template:
    metadata:
      labels:
        k8s-app: uav-api
        app: uav-api-deployment
    spec:
      containers:
      - name: uav-api-container
        image: ${DOCKER_IMAGE_TAG}
        env:
          - name: APP_ENV
            value: "live"
          - name: GUNICORN_WORKERS
            value: "2"
          - name: GUNICORN_WORKER_TIMEOUT
            value: "360"
          - name: "GUNICORN_RELOAD"
            value: True
          - name: SERVICE_NAME
            value: "uav-api"
          - name: API_PORT
            value: "3000"
          - name: APP_ENV
            value: "local"
          - name: SERVICE_HANDLER_API_ADDRESS
            value: "http://service-handler-api:3000"
          - name: PRIVATE_KEY_TEST
            value: "private-key-test"
          - name: PUBLIC_KEY_TEST
            value: "public-key-test"
          - name: INTERNAL_TOKEN
            value: "internal@123"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 930m
            memory: 650Mi
          requests:
            cpu: 150m
            memory: 300Mi
        livenessProbe:
          httpGet:
            path: /health_check
            port: 3000
            httpHeaders:
              - name: Authorization
                value: "***"
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 150
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health_check
            port: 3000
            httpHeaders:
              - name: Authorization
                value: "***"
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 2
          failureThreshold: 3
          timeoutSeconds: 2
      terminationGracePeriodSeconds: 62
